Server op på master
Fnux8890/3.SEM-LT pull request #2
Opened 2021-10-06 10:51 UTC by Sebastian689

2021-10-06 12:43 UTC, Fnux8890 requested changes

2021-10-06 12:43 UTC, Fnux8890 commented on app.js
> +const gate = 3000
Bør ændres til port, da det er den korrekte beskrivelse

2021-10-06 12:43 UTC, Fnux8890 commented on app/controller/routes/routes.js
> +const express = require('express')
Mere generelt.
fil navnet bør ikke hedde routes men være mesres specifikt, da alle routes ikke børe være under samme script.

2021-10-06 13:15 UTC, Livthraser commented on app/controller/middleware/async.js
> +  }
Jeg har brug for nogen forklarer den her til mig på et tidspunkt

2021-10-06 13:37 UTC, Livthraser commented on app/models/users.js
> +module.exports = mongoose.model("User", UserSchema)
Jeg har brug for at få forklaret kort, hvordan de her schemaer fungerer

2021-10-06 13:38 UTC, Livthraser approved these changes

2021-10-06 19:51 UTC, jaflo18 approved these changes

2021-10-07 09:02 UTC, ireneandrea approved these changes

2021-10-07 13:20 UTC, Sebastian689 commented
ServerSetup merges med master

2021-10-07 13:24 UTC, merged