module-overview into master(check description)
Fnux8890/3.SEM-LT pull request #8
Opened 2021-11-02 10:32 UTC by Sebastian689

Funktionaliteten på module-overview er færdig. Mangler dog at lave således at den kan tjekke om brugeren er færdig med exercisen så der kan være et checkmark over exercisen. Tænker at vente til det er lavet i exercise1 så jeg kan teste det derfra.

2021-11-02 13:44 UTC, jaflo18 requested changes

2021-11-02 13:44 UTC, jaflo18 commented on app.js
> +//const insertNavbar = require('./app/controller/middleware/insertNavbar')
Hvorfor er navbaren kommenteret ud?

2021-11-02 13:44 UTC, jaflo18 commented on app/views/css/modules.css
> +@import url('https://fonts.googleapis.com/css?family=Raleway');
Ikke godt at pushe noget css op vi alligevel skal væk fra.

2021-11-02 13:44 UTC, jaflo18 commented on app/views/pages/createaccount.pug
> -        include ./Navbar/navbar
Skal den ikke vises på create account side?

2021-11-03 08:19 UTC, Sebastian689 commented on app.js
> +//const insertNavbar = require('./app/controller/middleware/insertNavbar')
Den udgave af masteren jeg kopierede fra var navbaren bugged

2021-11-04 08:24 UTC, closed without merging